"""Add new column in Article

Revision ID: fdc7d66b5b31
Revises: f51c16693796
Create Date: 2021-03-20 19:03:10.557207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdc7d66b5b31'
down_revision = 'f51c16693796'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('is_verified', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'is_verified')
    # ### end Alembic commands ###
